### ISSUE TITLE
Error:   Cannot open file 'res://addons/dialogue_trees/scenes/dialogue_nodes/subscenes/case_text.tscn'.

### ISSUE THREAD

**Issue by GeminiSquishGames** [Ardot66/DialogueTrees#1]
Cannot open file 'res://addons/dialogue_trees/scenes/dialogue_nodes/subscenes/case_text.tscn'.
  
  I think you mean 'res://addons/dialogue_trees/scenes/dialogue_nodes/helper_nodes/case_text.tscn'

in DialogSwitchNode.cs @ line 14 should be:

_caseTextPath = $"{DialogueTreesPlugin.DialogueTreesPluginPath}/scenes/dialogue_nodes/helper_nodes/case_text.tscn",

Did a pull req here: #2 (figured helper_nodes sounded more descriptive than subscenes, but I'm not sure of the context or which you want to change, 🤔)

**Comment by Ardot66** [comment]
Thanks for noticing this, I really appreciate the help!
